### ISSUE TITLE
Design the HomePage Section of the page.

### ISSUE THREAD

**Issue by Saurav-Shrivastav** [MicrosoftStudentChapter/MAKEATHON#2]
- Follow the <a href="https://github.com/MicrosoftStudentChapter/MAKEATHON/blob/main/CONTRIBUTIONS.md">Contributions.md</a>
- Adhere to the design guidelines.
- Make sure that the page is responsive.

<hr>

### Folder Structure - 
```
| - templates/
    | - homepage/
        | - index.html
        | - static/
            | - css/
            | - images/
            | - js/
```

<hr>

### Resources - 
- SideNav - https://www.w3schools.com/howto/howto_js_sidenav.asp
- Countdown - https://www.w3schools.com/howto/howto_js_countdown.asp

<hr>

Team Size - 5
Issue will be reassigned in 2 days in case of failure.

**Comment by nitanshjain** [comment]
I would like to work on this

**Comment by darshpat01** [comment]
i would like to work on this

**Comment by mannadamay12** [comment]
I would love to work on this.

**Comment by NEHA15012002** [comment]
I would like to work on this

**Comment by Anureet123** [comment]
i would like to work on this

**Comment by Kriti-bit** [comment]
I'd like to work on this

**Comment by caffeinated4ighs** [comment]
I'd like to work on this

**Comment by ChiragG2101** [comment]
i would like to take this up

**Comment by anannyasingh610** [comment]
I am willing to work on this. :)

**Comment by abhinavmehra4** [comment]
I would like to work on this particular issue.

**Comment by harshita34** [comment]
i would like to this :)

**Comment by khushipr** [comment]
I would like to work on this.

**Comment by ChiragG2101** [comment]
I would like work on it
