### ISSUE TITLE
Change Alignment of About-Makeathon Page

### ISSUE THREAD

**Issue by SupritBehera** [MicrosoftStudentChapter/MAKEATHON#27]
Change alignment of the page from left to right, in accordance to the Figma design

**Comment by abhinavmehra4** [comment]
I would like to work on this issue.

**Comment by anannyasingh610** [comment]
I am willing to take this up. :)

**Comment by harshita34** [comment]
I want to take this up.

**Comment by SupritBehera** [comment]
Hey, sorry guys should have mentioned it in the issue itself, the About-Makeathon page was assigned to us and this was an issue we created so that we could send in another PR to change something we did not address in the original PR we sent in yesterday.
