### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by Saurav-Shrivastav** [MicrosoftStudentChapter/MAKEATHON#3]
- Follow the <a href="https://github.com/MicrosoftStudentChapter/MAKEATHON/blob/main/CONTRIBUTIONS.md">Contributions.md</a>
- Adhere to the design guidelines.
- Make sure that the page is responsive.

<hr>

### Folder Structure - 
```
| - templates/
    | - FAQ/
        | - faq.html
        | - static/
            | - css/
            | - images/
            | - js/
```

<hr>

### Resources - 
https://getbootstrap.com/docs/5.0/components/accordion/

<hr>

Team Size - 5 (max)
Issue will be reassigned in 2 days in case of failure.

**Comment by Ishaan-10** [comment]
I want to work on this

**Comment by ghost** [comment]
I want to work on this

**Comment by Kamalpreet-3223** [comment]
I'm willing to work on this

**Comment by Shreyasrana18** [comment]
i want to work

**Comment by pranjal-arora** [comment]
I want to take this up.

**Comment by mannadamay12** [comment]
I would love to be a part of this

**Comment by kumaraadarsh17** [comment]
I want to work on this.

**Comment by anannyasingh610** [comment]
I want to work on this. :)

**Comment by harshita34** [comment]
I am willing to work on this :)

**Comment by abhinavmehra4** [comment]
I want to work on this issue.

**Comment by girikgarg** [comment]
I want to work on this issue.

**Comment by RGTechPro** [comment]
I would like to work on it!!

**Comment by sanya1501** [comment]
i want to work on this

**Comment by ChiragG2101** [comment]
i would like to work on this issue
