### ISSUE TITLE
Modify the Speakers and Judges page

### ISSUE THREAD

**Issue by Saurav-Shrivastav** [MicrosoftStudentChapter/MAKEATHON#32]
- The arrows is yet to be made into action via JS function.
- In Safari and Mozilla browser only the (".abcd" div(sundar pichai's image)) is changing position. Other browsers all the other elements are working fine.
- Add animations to the info box card.
- Resolve Responsiveness issues

**Comment by MJ-06** [comment]
I would like to take this up (I took part in about pages)

**Comment by Ishaan-10** [comment]
Would like to take this up

**Comment by harshita34** [comment]
I want to work on this:)

**Comment by mannadamay12** [comment]
I would love to work on this.

**Comment by darshpat01** [comment]
I'd like to work on this

**Comment by abhinavmehra4** [comment]
I want to work on this issue

**Comment by Vanshika2411s** [comment]
I'd like to work on this issue!

**Comment by kumaraadarsh17** [comment]
i want to work on this

**Comment by SupritBehera** [comment]
I'd like to work on this
