### ISSUE TITLE
Prizes Page

### ISSUE THREAD

**Issue by Saurav-Shrivastav** [MicrosoftStudentChapter/MAKEATHON#34]

**Comment by abhinavmehra4** [comment]
I would really like to work on this issue.

**Comment by prabs3257** [comment]
i would like to work on this issue

**Comment by MJ-06** [comment]
I would like to work on this issue

**Comment by ghost** [comment]
Would like to work on this

**Comment by aarushi353** [comment]
I would like to work on this

**Comment by nitanshjain** [comment]
I would like to work on this

**Comment by anannyasingh610** [comment]
I would like to take this up. :)

**Comment by kumaraadarsh17** [comment]
I would like to work on this

**Comment by khushipr** [comment]
I would like to work on this

**Comment by sudiksha7** [comment]
I would like to work on this

**Comment by harshita34** [comment]
I want to take this up

**Comment by pranjal-arora** [comment]
I would like to take this up.

**Comment by NEHA15012002** [comment]
I would like to take this up

**Comment by girikgarg** [comment]
I would like to work on this

**Comment by darshpat01** [comment]
I'd like to work on this

**Comment by ChiragG2101** [comment]
i would like to work on this issue

**Comment by Ishaan-10** [comment]
Hi, I would like to work on this issue. (Have been assigned this according to the list)
