### ISSUE TITLE
Timeline Page

### ISSUE THREAD

**Issue by Saurav-Shrivastav** [MicrosoftStudentChapter/MAKEATHON#35]

**Comment by ChiragG2101** [comment]
I would like to work on this issue.

**Comment by Kamalpreet-3223** [comment]
I would like to work on this issue.

**Comment by thetarandhiman** [comment]
I would like to work on this issue.

**Comment by Vanshika2411s** [comment]
I would like to work on this issue.

**Comment by harshita34** [comment]
I want to work on this

**Comment by yashikaagg1110** [comment]
i would like to work on this

**Comment by anannyasingh610** [comment]
I would like to take this up. :)

**Comment by Kriti-bit** [comment]
I'd like to work on this

**Comment by abhinavmehra4** [comment]
I want to work on this issue

**Comment by Prajit-Sengupta** [comment]
I would like to take this up!

**Comment by MJ-06** [comment]
I would like to take this up

**Comment by prateekrusta** [comment]
I would like to take this up

**Comment by ritikrajdev** [comment]
Issue Resolved
