### ISSUE TITLE
FAQ page changes

### ISSUE THREAD

**Issue by Priya2123** [MicrosoftStudentChapter/MAKEATHON#36]
- remove the scrolls 
-  font size
- background color from blue to translucent

**Comment by ShreyaChopra13** [comment]
I want to take up this issue

**Comment by Kriti-bit** [comment]
I'd like to work on this

**Comment by yashikaagg1110** [comment]
i would like to work on this

**Comment by yashikaagg1110** [comment]
i would like to work on this

**Comment by darshpat01** [comment]
I'd like to work on this
