### ISSUE TITLE
About MLSC and About Makeathon pages (2 separate but similar pages) 

### ISSUE THREAD

**Issue by pranjalgupta29** [MicrosoftStudentChapter/MAKEATHON#4]
- Follow the <a href="https://github.com/MicrosoftStudentChapter/MAKEATHON/blob/main/CONTRIBUTIONS.md">Contributions.md</a>
- Adhere to the design guidelines.
- Make sure that the page is responsive.
<hr>

### Folder Structure - 
```
| - templates/
    | -About MLSC/
        | - aboutMLSC.html
        | - static/
            | - css/
            | - images/
            | - js/
    | -About Makeathon3077/
        | - aboutMakeathon.html
        | - static/
            | - css/
            | - images/
            | - js/

```

<hr>

### Resources - 
- Border Effect - https://youtu.be/t7dWFUggkno

<hr>

Team Size - 4 max
The issue will be reassigned in 2 days in case of failure.

**Comment by SupritBehera** [comment]
I'm willing to work on this

**Comment by aarushi353** [comment]
I want to do this

**Comment by ShreyaChopra13** [comment]
I want to work on this

**Comment by MJ-06** [comment]
i want to work on this

**Comment by Ishaan-10** [comment]
I want to work on this

**Comment by pranjal-arora** [comment]
I want to take this up.

**Comment by mannadamay12** [comment]
I would love to work on this.

**Comment by Anureet123** [comment]
i want to work on this

**Comment by anannyasingh610** [comment]
I am willing to work on this. :)

**Comment by harshita34** [comment]
I am interested to work on this :)

**Comment by abhinavmehra4** [comment]
I am interested in taking this up.

**Comment by ARSHIYA2602** [comment]
I am willing to take this up

**Comment by ChiragG2101** [comment]
i would like to work on this issue
