### ISSUE TITLE
Animations Required

### ISSUE THREAD

**Issue by ritikrajdev** [MicrosoftStudentChapter/MAKEATHON#46]
- Animation on homepage mobile view for opening and closing of navbar. (on clicking hamburger icon the width of opened navbar should go from 0 to the final/desired width).

- Fade In or Slide In Animation of Title and all other contents in About Pages.

- Judges and Speakers Page, Animation on Button Clicks should scale from 0 to 1 and 1 to o for showing and hiding respectively

Resources :-
https://www.youtube.com/watch?v=jgw82b5Y2MU&list=PL4cUxeGkcC9iGYgmEd2dm3zAKzyCGDtM5
https://animate.style/

**Comment by MJ-06** [comment]
i would like to take up the homepage animations

**Comment by mannadamay12** [comment]
I would love to take up about page animation

**Comment by ChiragG2101** [comment]
i would love to take up this issue

**Comment by ChiragG2101** [comment]
i would like to take this issue up
