### ISSUE TITLE
Speaker and Judges Page

### ISSUE THREAD

**Issue by ritikrajdev** [MicrosoftStudentChapter/MAKEATHON#5]
- Follow the <a href="https://github.com/MicrosoftStudentChapter/MAKEATHON/blob/main/CONTRIBUTIONS.md">Contributions.md</a>
- Adhere to the design guidelines.
- Make sure that the page is responsive.

### Folder Structure -
```
| - templates/
    | - speakers_and_judges/
        | - index.html
        | - static/
            | - css/
            | - images/
            | - js/
```

### Resources -

<hr />

Team Size - 4 (max)
Issue will be reassigned in 2 days in case of failure.

**Comment by sudiksha7** [comment]
I want to work on this.

**Comment by Prajit-Sengupta** [comment]
I am in

**Comment by shristigupta1408** [comment]
I want to take this up

**Comment by ghost** [comment]
I'm willing to work on this

**Comment by Kamalpreet-3223** [comment]
I'm willing to work on this

**Comment by Mhuskan** [comment]
I am interested in this.

**Comment by Pranjali012** [comment]
I want to work on this

**Comment by caffeinated4ighs** [comment]
I'd like to work on this one!

**Comment by RGTechPro** [comment]
I would like to work on it!!

**Comment by prateekrusta** [comment]
I am in

**Comment by ARSHIYA2602** [comment]
I would like to work on this

**Comment by ChiragG2101** [comment]
i would like to work on this issue
