### ISSUE TITLE
Sponsors Page

### ISSUE THREAD

**Issue by ritikrajdev** [MicrosoftStudentChapter/MAKEATHON#53]
Make a sponsors page including the animation of scrolling Buttons.

https://www.figma.com/file/DT9Q16fZUdgQDTo7MjQttW/Untitled?node-id=0%3A1

**Comment by anannyasingh610** [comment]
I would like to take this up.

**Comment by harshita34** [comment]
I would like to do this

**Comment by prateekrusta** [comment]
I would like to take up this issue

**Comment by Prajit-Sengupta** [comment]
Am in...

**Comment by ritikrajdev** [comment]
Issue Resolved
