### ISSUE TITLE
Tracks Page

### ISSUE THREAD

**Issue by pranjalgupta29** [MicrosoftStudentChapter/MAKEATHON#6]
- Follow the <a href="https://github.com/MicrosoftStudentChapter/MAKEATHON/blob/main/CONTRIBUTIONS.md">Contributions.md</a>
- Adhere to the design guidelines.
- Make sure that the page is responsive.

<hr>

### Folder Structure - 
```
| - templates/
    | -Tracks/
        | - tracks.html
        | - static/
            | - css/
            | - images/
            | - js/

```

<hr>

### Resources - 
- Border Effect - https://codepen.io/StrutTower/pen/rOpXEd
This is an example of a loader but you have to implement it in the form of a component as represented in the design.
<hr>

Team Size - 4 max
The issue will be reassigned in 2 days in case of failure.

**Comment by Red-0111** [comment]
I am willing to take this up.

**Comment by Mhuskan** [comment]
I am interested in this.

**Comment by khushipr** [comment]
I would like to work on this issue

**Comment by VDliveson** [comment]
**Hello there,
I am interested to contribute in this section**

**Comment by yashikaagg1110** [comment]
i would like to take this up

**Comment by harshita34** [comment]
I would like to work on this :)

**Comment by anannyasingh610** [comment]
I am willing to work on this. :)

**Comment by ChiragG2101** [comment]
i would like to work on this issue

**Comment by ChiragG2101** [comment]
i am willing to work on this issue

**Comment by anannyasingh610** [comment]
I am willing to take this up. :)

**Comment by prabs3257** [comment]
i am willing to work on this issue

**Comment by thetarandhiman** [comment]
I would like to take up this issue.
